export const COMMON_ACCESSORIALS = [
  'Liftgate Pickup',
  'Liftgate Delivery',
  'Inside Pick Up',
  'Inside Delivery',
  'Limited access Pick Up',
  'Limited Access Delivery',
  'Pickup Appointment',
  'Delivery Appointment',
  'Protect From Freezing',
  'Residential Delivery',
];

export const GENERAL_ACCESSORIALS = [
  'Air Ride truck',
  'Bonded',
  'Bonded + Form 7512',
  'Double Blind',
  'Envelope(s)',
  'Guaranteed transit time',
  'Guns handling license',
  'Hazmat 2.3',
  'Hazmat Explosives 1.4',
  'Hazmat Toxic or Poison 6.1',
  'Household Goods',
  'Liquids',
  'Liquor Handling License',
  'Loose Boxes',
  'Packaging type: Bundle(s)/Roll(s)/Tube(s)',
  'Pallets-Crates-Skids',
  'Protect From Freezing',
  'Tobacco handling license',
  'TSA Approved carrier',
  'Dock Height',
  'Free Insurance coverage',
  'Lock Bars',
  'Loose Cargo',
  'Straps',
  'TWIC Card',
  'Non Hazmat',
  'One day chassis discount',
  'Seafood',
  'Binders',
  'Tarp 4/6/8 ft',
  'Overweight',
  'Reefer',
  'Hazardous Material Handling',
];

export const ORIGIN_ACCESSORIALS = [
  'Airport Pick Up',
  'Blind Pick Up',
  'Distribution Center Pickup',
  'Inside Pick Up',
  'Jacinto Port Pickup',
  'Limited access Pick Up',
  'Lumper Loading Assistance',
  'Port Pick Up',
  'Pickup Appointment',
  'Wash out',
];

export const DELIVERY_ACCESSORIALS = [
  'Adult Signature Required (Parcel)',
  'Airport Delivery',
  'Amazon Warehouse Delivery',
  'Blind Delivery',
  'Costco Delivery',
  'Curbside Delivery',
  'Delivery Appointment',
  'Distribution Center Delivery',
  'Inside Delivery',
  'Jacinto Port Delivery',
  'Limited Access Delivery',
  'Lumper Unloading Assistance',
  'Pick Up at Carrier Destination Terminal',
  'Port Delivery',
  'Signature Required (Parcel)',
  'Threshold Delivery',
  'Trade Show Delivery',
  'Walmart Delivery',
  'Airport delivery (TSA)',
];

export const NMFC_CLASSES = [
  '50', '55', '60', '65', '70', '77.5', '85', '92.5',
  '100', '110', '125', '150', '175', '200', '250', '300', '400', '500',
];

export const PACKAGE_TYPES = [
  'Pallet',
  'Skid',
  'Box / Carton',
  'Crate',
  'Bundle',
  'Roll',
  'Tube',
  'Drum / Barrel',
  'Tote / Gaylord',
  'Bale',
  'Loose / Pieces',
];
